zaproxy/zap-api-java

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ApiResponseSet.java
Change ApiResponseSet to allow to obtain the keys, values and the map.
Deprecate unused method and constructor.
---
From talks in IRC.
Version was not bumped, per changes in #4.
=> Allow to obtain all data of an ApiResponseSet

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java, subprojects/zap-clientapi/zap-clientapi.gradle
Regenerate the AJAX Spider API to match the latest version, which allows
to scan a context, as a user and just a subtree.
Bump minor version, per new functionality.
=> Regenerate AJAX Spider API (v16)

subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/authentication/FormBasedAuthentication.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Replace the calls of ApiResponseSet.getAttribute(String) with
getValue(String), which should have been done at the same time of the
deprecation.
Related to #5 - Allow to obtain all data of an ApiResponseSet
=> Remove usage of deprecated method

subprojects/zap-clientapi/zap-clientapi.gradle
Add a task to verify the binary compatibility of new artifacts, against
version 1.0.0.
=> Add task to verify artifacts' binary compatibility

subprojects/zap-clientapi/zap-clientapi.gradle
Change signing task to skip archive signing if there's no signing key ID
defined.
=> Skip archive signing if there's no signing key

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/Alert.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change Alert class to expose the alert ID, message ID and scanner ID.
Add "False Positive" to enum Alert.Confidence, which can be set in the
returned Alerts.
=> Expose Alert fields returned by ZAP API

subprojects/zap-clientapi/zap-clientapi.gradle
Add OWASP Dependency-Check plugin to check the publicly disclosed
vulnerabilities of the dependencies being used by ZAP API client.
=> Add plugin to check vulns of dependencies

subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/AlertCheckTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/AlertTask.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/Alert.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/AlertsFile.java
Change classes Alert and AlertTask to use name instead of alert for the
name of the alert, deprecate the alert setters/getters and add new ones
for the name.
Change other classes to use the new methods.
Related to zaproxy/zaproxy#1341 - Update alert XML schema to remove
element-level name collision
=> Use name for alerts

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java
Regenerate the Selenium API to match the latest version, which allows
to set the path to geckodriver. Also, add the description of the API
endpoints.
---
Contains changes from zaproxy/zaproxy#3177.
=> Regenerate Selenium API (v8)

subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/SimpleExample.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change ClientApi to allow to specify the ZAP API key when creating the
instance, to ensure that the API key is sent with all API requests.
Also, send it in the header not just as (query) parameter (for newer and
older versions of ZAP).
Update SimpleExample to indicate the new usage.
Related to zaproxy/zaproxy#3226 - Option to supply API key or nonces via
header
=> Allow to specify the API key through the ClientApi

subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ActiveScanSubtreeTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ActiveScanUrlTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/LoadSessionTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/NewSessionTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/SaveSessionTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/SpiderUrlTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/StopZapTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ZapTask.java, subprojects/zap-clientapi-ant/src/test/java/org/zaproxy/clientapi/ant/BuildTest.java, subprojects/zap-clientapi-ant/src/test/resources/org/zaproxy/clientapi/ant/build.xml, subprojects/zap-clientapi-ant/zap-clientapi-ant.gradle
Change the Ant tasks to allow to specify the API key (move the API key
attribute to base class ZapTask) as it might be required for newer ZAP
versions.
Add tests to check that the tasks accept the expected attributes and
nested elements.
=> Allow to specify the API key in all Ant tasks

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApiMain.java
Change ClientApiMain to set the API key into the ClientApi instead of
passing it in each action (the former sends the key with all API
requests).
=> Change ClientApiMain to use the API key "globally"

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/Alert.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ApiResponseElement.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ApiResponseSet.java
Change ApiResponseSet to not assume that the values of the set are of
the type ApiResponseElement (by changing the type of the values to
ApiResponse) and add helper method to return the values as String.
Change Alert to use the new method (to get the value(s) as String).
Change ApiResponseElement to return its value when toString() is called.
Fix zaproxy/zaproxy#3228 - ApiResponseElement casting error in
constructor of ApiResponseSet (if child is also a set)
=> Change value type of ApiResponseSet to ApiResponse

subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/StopZapTask.java
Change StopZapTask to remove the call to Throwable.printStackTrace(),
the exception is wrapped and thrown for the caller to handle (e.g. Ant
which already outputs the stack trace).
=> Remove printStackTrace from Ant task

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java
Regenerate the AJAX Spider API to match the latest version, which allows
to obtain the full results of a scan (requests in and out of scope and
requests with I/O errors).
=> Regenerate AJAX Spider API (v17)

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Acsrf.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Autoupdate.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Break.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/HttpSessions.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java
Regenerate core APIs for ZAP version 2.6.0 (some tweaks were done to
keep the API client binary compatible with previous versions).
=> Regenerate core APIs for ZAP version 2.6.0

CHANGES.md, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/AbstractActiveScanTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ActiveScanSubtreeTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ActiveScanUrlTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/SpiderUrlTask.java, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ZapTask.java, subprojects/zap-clientapi-ant/src/test/java/org/zaproxy/clientapi/ant/BuildTest.java
Change ActiveScanSubtreeTask, ActiveScanUrlTask, and SpiderUrlTask to
wait for the scans to finish before returning.
Refactor the active scan tasks to reduce code duplication (they differ
only on the parameters used to start the scan).
Update the tests to assert the new behaviour (i.e. scan tasks check the
status of the scans).
=> Update Ant tasks to wait for the scans to finish

CHANGES.md, subprojects/zap-clientapi-ant/src/main/java/org/zaproxy/clientapi/ant/ReportTask.java, subprojects/zap-clientapi-ant/src/test/java/org/zaproxy/clientapi/ant/BuildTest.java, subprojects/zap-clientapi-ant/src/test/resources/org/zaproxy/clientapi/ant/build.xml
Add a new task, ReportTask, that allows to create the ZAP report.
Add test to check that the new Ant task is called.
Fix zaproxy/zaproxy#3712 - Allow to create reports with Ant tasks
=> Add an Ant task to create ZAP reports

CHANGES.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Acsrf.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Authentication.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Authorization.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Autoupdate.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Break.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Context.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/ForcedUser.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/HttpSessions.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Params.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Script.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Search.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/SessionManagement.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Stats.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Users.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/CoreDeprecated.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/ScriptDeprecated.java
Regenerate core APIs for ZAP version 2.7.0 (some tweaks were done to
keep the API client binary compatible with previous versions).
=> Regenerate core APIs for ZAP version 2.7.0

subprojects/zap-clientapi/zap-clientapi.gradle
Update OWASP Dependency-Check plugin to latest version and set to skip
configuration used for binary compatibility tests (just needs to check
the current version).
=> Update OWASP Dependency-Check plugin to 3.0.2

.travis.yml, subprojects/zap-clientapi/zap-clientapi.gradle
Change .travis.yml to also run the build with Java 9.
Change japicmp task to not run by default in Java 9 (requires a module).
=> Add Java 9 to Travis CI builds

CHANGES.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change the ClientApi to disable the HTTP cache, while the API responses
shouldn't be cached it seems they were, sometimes, which broke some use
cases (e.g. poll the status of a scan).
Related to zaproxy/zaproxy#4462 - ZAP Jenkins plugin does not obtain
latest spider status
=> Explicitly disable HTTP cache in ClientApi

subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/authentication/FormBasedAuthentication.java
Change FormBasedAuthentication to correct the method used to obtain the
data from the API response to compare with correct type (String instead
of ApiResponse), which caused the mandatory parameters to be reported
as optional.
=> Correct form-based authentication example

build.gradle, subprojects/zap-clientapi-ant/zap-clientapi-ant.gradle, subprojects/zap-clientapi/zap-clientapi.gradle
The java-library plugin gives more control on how the dependencies are
exposed to consumers of the API client, update dependency declarations
accordingly.
=> Migrate to java-library plugin

subprojects/zap-clientapi/zap-clientapi.gradle
Configure examples sourceset to use the main sourceset and ensure the
examples are compiled.
=> Fix configuration of examples sourceset

.travis.yml, subprojects/zap-clientapi/zap-clientapi.gradle
Change .travis.yml to also run the build with Java 10.
Add a task/note about why japicmp is not run with newer Java versions.
=> Add Java 10 to Travis CI builds

CHANGELOG.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/AlertsFile.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change ClientApi to disable XXE processing (same as in ZAP) when parsing
ZAP API responses, not needed.
Change AlertsFile to close the file with try-with-resource statement to
ensure it is always closed.
Update CHANGELOG.md.
Issues reported by `lgtm.com`.
=> Fix misc issues

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/AlertsFile.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change AlertsFile to not print the exception, instead let it be handled
by caller code (as it's already doing).
Change ClientApi to provide a custom message when failed to save the
alerts.
=> Don't print exception when saving alerts

build.gradle, subprojects/zap-clientapi-ant/src/test/java/org/zaproxy/clientapi/ant/BuildTest.java, subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/SimpleExample.java, subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/authentication/FormBasedAuthentication.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApiMain.java
Change build.gradle to use Error Prone when compiling.
Address warnings reported by Error Prone:
- Add missing fail to BuildTest.shouldExecuteTargetAlertCheck to ensure
that the test does not pass if the expected exception is not thrown
(MissingFail).
- Change SimpleExample to not rely on default charset when writing the
report (DefaultCharset).
- Change FormBasedAuthentication to use ArrayList instead of LinkedList
(JdkObsolete).
- Change ClientApi to not rely on default charset when reading the
proxied response (DefaultCharset), also, use try-with-resource
statement to close the input stream, and normalise case of API key
parameters (InconsistentCapitalization).
- Change ClientApiMain to split the command line arguments with a limit
(StringSplitter) and add a missing case to the tasks' …
=> Add Error Prone to build

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Add JavaDoc to ClientApi.buildZapRequest to explain why the domain is
hardcoded.
=> Document why the API requests use hardcoded domain

subprojects/zap-clientapi/zap-clientapi.gradle
Update to latest version and use a detached configuration for the
checks.
Remove Java version check and manually added input no longer needed.
=> Update Gradle plugin for JApicmp

subprojects/zap-clientapi/zap-clientapi.gradle
Link to the site instead of the OWASP wiki page.
=> Update link in the POM

subprojects/zap-clientapi/src/examples/java/org/zaproxy/clientapi/examples/SimpleExample.java
Replaced the hard coded thread sleep with explicit API calls to
poll the number of records the passive scanner still has to scan.
=> SimpleExample - wait until the passive scanner completes

CHANGELOG.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Exim.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/ImportLogFiles.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Importurls.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/LocalProxies.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Network.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Replacer.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/AcsrfDeprecated.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/AscanDeprecated.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/ReplacerDeprecated.java, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/SpiderDeprecated.java, subprojects/zap-clientapi/zap-clientapi.gradle
Update core APIs for 2.12.0.
Add the APIs of the following add-ons:
- Import/Export version 0.3.0;
- Network version 0.3.0;
- Spider version 0.1.0.
Update the API of the following add-on:
- Replacer version 11.
Deprecate the following APIs:
- `ImportLogFiles`;
- `Importurls`;
- `LocalProxies`.
Update Gradle Plugin for japicmp.
=> Add/update APIs of add-ons and core

CHANGELOG.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Send only as an HTTP header, which is supported by ZAP since 2.6.0.
=> Stop sending API key as query parameter

.github/workflows/ci.yml
Use the latest versions, which addresses deprecation warnings.
Use Gradle actions for build/cache and wrapper validation.
=> Update actions in CI workflow

CHANGELOG.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Change the call API methods to allow to specify the method, if not GET the parameters are sent in the body.
=> Allow to call the API with custom HTTP method

CHANGELOG.md, subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
Add support for JSON API calls with new method callApiJson.
Background:
There are some API methods (e.g. alert/view/alertCountsByRisk) which only work with JSON as the requested response format. Not using JSON (this is a different bug) will result in an "Internal Error" (e.g. Alert#alertCountsByRisk(String, String)).
The new method callApiJson allows java client API users to request a JSON response. We now also can create/build JSON models (e.g. with/for GSON) further enhancing the APIs usability.
=> Add method to get JSON responses

CHANGELOG.md, README.md, build.gradle.kts
Update version, readme, and changelog for new release.
=> Release 1.16.0
