subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java

Regenerate the Selenium API to match the latest version, which allows
to choose which Firefox binary is used.
---
Version was not bumped, per changes in #4.

Regenerate Selenium API (v7)

---

subprojects/zap-clientapi/zap-clientapi.gradle

Add a description and add it to the build tasks.

Add description to uberJar task

---

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AlertFilter.java

Generate the Context Alert Filters API, not previously included in the
API client.

Generate Context Alert Filters API (v3)

---

README.md

Add instructions on how to build, install and release the artifacts.

Update README with instructions to build/release

---

CHANGES.md

Add a file with the changes done to the versions, easier to track the
changes and build the release notes of each version.

Add change log

---

CHANGES.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Importurls.java

Add the API of the add-on "Import files containing URLs" (version 3).

Add Importurls API

---

CHANGES.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Openapi.java

Add the API of the add-on "OpenAPI Support" (version 5).

Add Openapi API

---

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Openapi.java

Regenerate the API of the add-on "OpenAPI Support" (upcoming version 6).

Regenerate Openapi API

---

CHANGES.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Replacer.java

Add the API of the add-on Replacer (to be released).

Add replacer API

---

subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Reveal.java

Regenerate the API of Reveal add-on (just doc updates).

Regenerate reveal API

---

build.gradle

Update version to latest released version (1.5.0).

Update version for binary compatibility checks

---

CHANGES.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Websocket.java

Add the API of WebSockets add-on (version 15).

Add websocket API

---

build.gradle

Address deprecation by using default wrapper task.

Address Gradle deprecation

---

README.md

Update link to search in Maven Central, now using query parameters.
Add mention to Gradle.

Tweaks in README

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Soap.java

Add the API of SOAP Scanner add-on (version 3).

Add soap API

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Importurls.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Replacer.java

Update Replacer API, per release of version 7.
Add description to Importurls API endpoint.

Update Replacer and Importurls

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Alert.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Authentication.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Autoupdate.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Context.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/HttpSessions.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Script.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Search.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/SessionManagement.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Users.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/CoreDeprecated.java

Address deprecations and move methods to keep the API client binary
compatible with previous versions.

Regenerate core APIs for 2.8.0

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AlertFilter.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Websocket.java

Update the APIs of the following add-ons:
- Context Alert Filters version 8;
- Selenium version 15.0.0;
- WebSockets version 19.

Update APIs of add-ons

---

CHANGELOG.md
README.md
build.gradle

Prepare next dev iteration

---

README.md

Signed-off-by: Simon Bennetts <psiinon@gmail.com>

Refer to the main repo for the help links

---

CHANGELOG.md

Update help link

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AccessControl.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Alert.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AlertFilter.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Autoupdate.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Break.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Exportreport.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Replacer.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Revisit.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Script.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Wappalyzer.java

Regenerate core and add-ons APIs.

Regenerate APIs

---

CHANGELOG.md
README.md
build.gradle
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Acsrf.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Alert.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Context.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Graphql.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Users.java

Regenerate core and add-ons APIs.
Update version, readme, and changelog for new release.

Release 1.9.0

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Automation.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java

- Add the APIs of the following add-ons:
- Network version 0.2.0;
- Update the APIs of the following add-ons:
- Automation Framework version 0.15.0;
- Selenium version 15.8.0;
- Add a graphql object to ClientApi (resolves zaproxy/zaproxy#7262).
Signed-off-by: Akshath Kothari <github@ricekot.com>

Update add-on APIs

---

CHANGELOG.md
README.md
build.gradle

Update version, readme, and changelog for new release.

Release 1.11.0

---

CHANGELOG.md
README.md
build.gradle
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AlertFilter.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Graphql.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Network.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/AlertFilterDeprecated.java

Update core APIs for 2.13.0.
Update the APIs of the following add-ons:
- AJAX Spider version 23.15.0;
- Alert Filters version 17;
- GraphQL Support version 0.18.0;
- Network version 0.10.0;
- Selenium version 15.13.0;
- Spider version 0.5.0.
Prepare release.

Update APIs of add-ons and core

---

README.md
subprojects/zap-clientapi-ant/zap-clientapi-ant.gradle
subprojects/zap-clientapi/zap-clientapi.gradle

Update docs and POM

---

CHANGELOG.md
README.md
build.gradle.kts

Update version, readme, and changelog for new release.

Release 1.13.0

---

CHANGELOG.md
README.md
build.gradle.kts
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Ascan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Core.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Search.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Wappalyzer.java

Update core APIs for 2.15.0.
Prepare release.

Update APIs of core and release 1.14.0

---

CHANGELOG.md
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/core/ClientApi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/AjaxSpider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Exim.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Oast.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Openapi.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Pscan.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Replacer.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Script.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Search.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Selenium.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/Spider.java
subprojects/zap-clientapi/src/main/java/org/zaproxy/clientapi/gen/deprecated/OpenapiDeprecated.java

Update core APIs for 2.16.0.
Add/update the APIs of the add-ons.

Update APIs and release 1.15.0

---

README.md
build.gradle.kts

Remove SNAPSHOT and update readme.

Update version for release

---

README.md

The integration is no longer working.

Remove oudated badge in README
